### ISSUE TITLE
ANSI color processing isn't enabled on Windows by default

### ISSUE THREAD

**Issue by Mirsario** [nidnogg/zeitfetch#12]
Please see the top answer here:
https://superuser.com/questions/413073/windows-console-with-ansi-colors-handling

Following the registry workaround I turned zeitfetch's output from this:
> ![image](https://github.com/nidnogg/zeitfetch/assets/6795251/7538bc50-44bc-4b92-8d67-8577ea82eaf1)

to this:
> ![image](https://github.com/nidnogg/zeitfetch/assets/6795251/bf859f81-8c43-41ae-8f24-5ee28504e496)

But as stated earlier in the SO answer, a `SetConsoleMode(hConsoleHandle, ENABLE_VIRTUAL_TERMINAL_PROCESSING)` call should spare all future users of this tiny hassle.

**Comment by nidnogg** [comment]
Heya, thanks for reporting this! I hadn't tested on Windows for a while. This is specifically on Command Prompt, right? I'll look into incorporating this for the next release

**Comment by Mirsario** [comment]
Perhaps Win11 or some Win10 update I don't have have rectified this? If not - note that the `VirtualTerminalLevel` value can be in any subkey of `Console`, removing it from everywhere should break things again for you. But if you just push a fix I'll recompile & test it for you if needed.
