### ISSUE TITLE
Incorrect dark and bright white ANSI color

### ISSUE THREAD

**Issue by vladdeSV** [nidnogg/zeitfetch#18]
The white ANSI colors are incorrect. The right-most colors should be "dark white" and "bright white", but instead I see "bright dark" and "foreground color"

![incorrect](https://github.com/user-attachments/assets/14fad14c-4495-4946-ab2a-b00174c1e5ec)

## Expected
I would expect to see this instead:
![expected](https://github.com/user-attachments/assets/3fc130f2-55b3-4271-bb25-d6ec52198f33)

**Comment by nidnogg** [comment]
Heya, thanks for pointing this out. Seems like a reasonably quick fix.
I will be slotting some time for this soon but I'll label it as a `good first issue` if anyone else wants to take it up in the meantime.
